# Generated by Django 4.1 on 2022-08-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='genre',
            new_name='category',
        ),
    ]
