# Generated by Django 4.1 on 2022-08-26 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_rename_genre_category_rename_genre_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='got_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
