# Generated by Django 4.1 on 2022-08-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_iteminstance_got_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_renewed', 'Set Item as renewed'),)},
        ),
    ]
