# Generated by Django 4.1 on 2022-08-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_item_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
