# Generated by Django 4.1 on 2022-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_item_category_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['type_name', 'compeny_name']},
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
        migrations.AddField(
            model_name='store',
            name='compeny_name',
            field=models.CharField(default=' ', help_text='Enter a compeny name', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='type_name',
            field=models.CharField(default=' ', help_text='Enter a type name', max_length=100),
        ),
    ]
